### ISSUE TITLE
Adding support for a VariableStatement with more than one declaration

### ISSUE THREAD

**Issue by jdalrymple** [Swatinem/rollup-plugin-dts#112]
What would be the best way to go about implementing this functionality?  I could try and throw together a PR.

**Comment by Swatinem** [comment]
I suspect this will be quite hacky, but it should work.

I currently do some pre-processing before *really* parsing the file here: https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/reorder.ts

I think one of those pre-processing steps could be to just split up one `VariableStatement` with multiple declarators into separate statements. That way each one of those can be handled independently and we don’t have to worry what happens if rollup decides to DCE on of the declarators, but not the other.

On a related note, I have some ideas about cleaning all that up, and also give the different steps more sensible names.

**Comment by jdalrymple** [comment]
Hmm, well if you can outline some of those changes in a issue, i can help tackle some of them!
