### ISSUE TITLE
declarationMap support

### ISSUE THREAD

**Issue by kacpak** [Swatinem/rollup-plugin-dts#113]
Hi, I haven't found information about it and I cannot test it out to verify myself this week, but I'm wondering if this plugin supports TypeScript's declaration map support?
If no - would you consider adding it in?

**Comment by Swatinem** [comment]
So rollup on its own has excellent sourceMap support. But we do some pre- and post-processing of whatever rollup does, apart from the synthetic AST that I generate. And I really don’t want to manually maintain a sourceMap for all that.

I suspect doing that is a huge amount of work, and I certainly don’t want to do that on my own :-D

**Comment by segevfiner** [comment]
@Swatinem Does https://www.npmjs.com/package/magic-string help?

**Comment by Swatinem** [comment]
Yes, `magic-string` would help here, and I converted the *preprocessor* code to it some time ago. There is also postprocessor code that fixes up some namespace declarations which would also need to be adapted to `magic-string`. I never got around to that.

PRs welcome though.

**Comment by aleclarson** [comment]
Should keep this open in case someone wants to tackle it. But tag it with ”help wanted”.

**Comment by charlesritchea** [comment]
@NWYLZW hey, I tried using your fork as a drop-in replacement because I'm trying to solve IntelliJ/WebStorm resolving declarations going to the dts bundle d.ts. I have no idea if it will help, but anyway when I just did a drop in replacement I'm getting this error
```
[!] (plugin dts) Error: Module /home/bar/Projects/wireframe-tool/packages/foo-common/dist/dts/index.d.ts is not included in the tsconfig project: ./tsconfig.json
```
I even tried using a special tsconfig that did include that, but got the same error. Anyway idea what's going on?
