### ISSUE TITLE
Is there a way to have namespaces declarations not relying on exports?

### ISSUE THREAD

**Issue by ricardomatias** [Swatinem/rollup-plugin-dts#124]
I'm trying to use the declaration file of my library with [monaco editor](https://microsoft.github.io/monaco-editor/index.html) which doesn't support `export` in the declaration file. Because of this I have to remove the exports, which leaves me with weirdly named namespaces.

Example in Visual Studio Code:
[
![Screenshot from 2020-10-26 13-27-18](https://user-images.githubusercontent.com/8850708/97172328-2bf26480-178f-11eb-9a06-6e7eae09b63e.png)
](url)

Definition:
![Screenshot from 2020-10-26 13-29-59](https://user-images.githubusercontent.com/8850708/97172502-63611100-178f-11eb-8e61-1d023a3a5057.png)

The example shows the intermediate name as well, instead of the exported one.

I'm aware that there are 2 different issues at play, but the answer to the title could solve them both.

**Comment by Swatinem** [comment]
I think I understand what you want to achieve, but lets clarify:

You would like the resulting code to look something like this:

```ts
namespace Tools {
  namespace Euclidean {
    declare const create: (pulses: number, beats: number) => BinaryEvent[];
  }
}
```

I guess you are doing a `export * as Euclidean from …` somewhere?

The problem is twofold:
1. typescript "namespace" declarations are super weird sometimes, lol.
2. rollup itself flattens all the items into the root module, and then re-creates these nested namespace-exports by creating objects. Thats what I transform into these synthetic "namespace" declarations. They certainly are suboptimal.

I wonder what other construct I could use that better reflects the intended usage here.

**Comment by ricardomatias** [comment]
Yes I'm doing ` export * as Euclidean from …`, but just one namespace (the Tools is just for the docs)

```typescript
namespace Euclidean {
    declare const create: (pulses: number, beats: number) => BinaryEvent[];
}
```
I guess the above would work with the import suggestions + type definitions shown properly.

**Comment by Swatinem** [comment]
Since rollup puts the `create` in the global scope, I can’t just "re-export" it from a child, because the inner definition shadows the outer, thats why I have to work around that by creating an alias.

I wonder if defining a const object has the same semantics as a namespace, as in:

```ts
declare const Euclidean: {
  create: typeof create,
};
```

I don’t think its the same, since you probably can’t use *types* from there.
