### ISSUE TITLE
Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

### ISSUE THREAD

**Issue by ghostdevv** [Swatinem/rollup-plugin-dts#178]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

I am running this on my code and it works fine, well I am using http://npmjs.com/tsup to bundle my typescript code for esm and cjs platforms.

I ran into a issue with it not generating `declare` on enums when used a certain way, I created a repro here: <https://github.com/ghostdevv/dts-plugin-enum-repo>

I know it doesn't ticket checkbox 2 but I think this is within the scope of a bug

**Comment by ghostdevv** [comment]
bump

**Comment by Swatinem** [comment]
I think the problem comes from your handcrafted `.d.ts` file:

https://github.com/ghostdevv/dts-plugin-enum-repo/blob/7e03e0a291cc7f81c4cf1a288fbbf32d67858980/src/test.d.ts#L1

It indeed is missing a `declare` modifier.

**Comment by ghostdevv** [comment]
@Swatinem I tested this and with exporting a enum with:

```ts
export declare enum TestEnum {
    A,
    B,
    C,
    D
}
```

it doesn't work

**Comment by everlose** [comment]
the same。tsc generate file `test.d.ts`

```
export declare type PushEvent = {...}
```

but，dts plugin roll the definition `index.d.ts`

```
declare type PushEvent = {...}
```

Lost `export`，my user cannot import this definition

**Comment by ashuvssut** [comment]
> the same。tsc generate file `test.d.ts`
> 
> ```
> export declare type PushEvent = {...}
> ```
> 
> but，dts plugin roll the definition `index.d.ts`
> 
> ```
> declare type PushEvent = {...}
> ```
> 
> Lost `export`，my user cannot import this definition

I have this issue too.

> @everlose Well are you exporting it again from the index.d.ts?
How to `export` from index.d.ts? It is generated by this plugin. It was exported from `test.d.ts` but when it got bundles by this plugin, that `export` keyword is lost

**Comment by Swatinem** [comment]
I mean obviously if you want something be exported from `index.d.ts` that originally lives in `test.d.ts` you gotta `export { PushEvent } from "./test";` or something similar.

**Comment by ashuvssut** [comment]
Hi @Swatinem . Thankyou for replying

Let me explain you through an example. I have setup a [test repo](https://github.com/ashuvssut/rollup-ts-test) to show you the exact problem. 
<details>
<summary>You can clone and test.
Expand to see Commands to setup && run the example </summary>
<br>
<code>
git clone https://github.com/ashuvssut/rollup-ts-test && cd rollup-ts-test  && yarn && yarn dev
</code>
</details>

So what happened? After we did `rollup -c`, TS compiler will generate the declatation `.d.ts`  files in the /@types (in tsconfig: `declarationDir: "/@types"`)
so you will see something like this:-
```
@types/
    |---- index.d.ts
    |---- types.d.ts
dist/
tsconfig.json
rollup.config.js
.
.
.
.
```
> **IMPORTANT** _Observe that `index.d.ts` & `types.d.ts` have `export` keywords_ that you were asking about

So, that `index.d.ts` is next fed to to rollup-plugin-ts (see `rollup.config.js`). this will result in bundling all `d.ts` file to `dist/index.d.ts`

Now Observe the problem in `dist/index.d.ts`. We lost the `export` keywords that were present in `d.ts` files in `@types/`

Hope this helps. Thanks

**Comment by Swatinem** [comment]
Yes, the only thing you are exporting from `index.ts` is this:

```
export { THEMES };
```

https://github.com/ashuvssut/rollup-ts-test/blob/f12cf5e62182d0bf2d0aafd405029411e0b9cf62/src/index.ts#L12

The other things are not being exported because you didn’t explicitly tell them to be. You can still refer to the other things indirectly, via `typeof THEMES`, if you absolutely want to. Otherwise you need to specifically re-export the stuff.

**Comment by ashuvssut** [comment]
@Swatinem yes thankyou. It makes sense now

I gave the plugin `input` option as `input: "./@types/index.d.ts",` and that's why only exported members of index.d.ts had the `export` keyword.
As you suggested to re-export all the stuff... [I followed that ]( https://github.com/ashuvssut/rollup-ts-test/blob/master/src/index.ts#L11) and I got what I wanted.

But now suppose there are 100+ such types from different different `types.ts` files... now I have to re-export all those 100+ types through `index.ts`.😫

I wish there was a easy way to do that

Anyways thankyou very much for bearing with my silly questions. I am just a TS newbie studying in college😅

**Comment by ashuvssut** [comment]
@Swatinem yes thankyou. It makes sense now

I gave the plugin `input` option as `input: "./@types/index.d.ts",` and that's why only exported members of index.d.ts had the `export` keyword.
As you suggested to re-export all the stuff... [I followed that ]( https://github.com/ashuvssut/rollup-ts-test/blob/master/src/index.ts#L11) and I got what I wanted.

But now suppose there are 100+ such types from different different `types.ts` files... now I have to re-export all those 100+ types through `index.ts`.😫 I wish there was a easy way to do that

Anyways thankyou very much for bearing with my silly comments and questions. I am just a TS newbie studying in college😅

**Comment by ghostdevv** [comment]
I would like to reclarify the original purpose of this issue. When using a enum in a ts file the built dts does not have a enum prefixed with the `declare` or `export` modifier. Which is invalid. I have the repro [here](https://github.com/ghostdevv/dts-plugin-enum-repo) and you can see the source and build result.

https://github.com/ghostdevv/dts-plugin-enum-repo

**Comment by Swatinem** [comment]
Your repro has a `index.ts` that does a `export * from './test';`, only that you have both a `test.ts` and `test.d.ts` file. It looks like the typescript resolution prefers the `.d.ts` file, which is missing the `declare` keyword.

It would be nice to resolve that ambiguity first, and create a repro that starts with **valid** `.d.ts` files. The `.ts` mode is a maintenance nightmare.

**Comment by ghostdevv** [comment]
> Your repro has a index.ts that does a export * from './test';, only that you have both a test.ts and test.d.ts file. It looks like the typescript resolution prefers the .d.ts file, which is missing the declare keyword.

it is my understanding and assumption from extensive use of enums that you do not require the declare keyword when you are exporting an enum.

> It would be nice to resolve that ambiguity first, and create a repro that starts with valid .d.ts files. The .ts mode is a maintenance nightmare.

You are right about this


---

I will close this issue as I am unable to re-reproduce this! thank you for your time

**Comment by hushaudio** [comment]
> 
Thanks so much declaring the enum as an export did it for me
`export enum MyEnum { PROP1, PROP2 };`

**Comment by hushaudio** [comment]
> > Your repro has a index.ts that does a export * from './test';, only that you have both a test.ts and test.d.ts file. It looks like the typescript resolution prefers the .d.ts file, which is missing the declare keyword.
> 
> it is my understanding and assumption from extensive use of enums that you do not require the declare keyword when you are exporting an enum.
> 
> > It would be nice to resolve that ambiguity first, and create a repro that starts with valid .d.ts files. The .ts mode is a maintenance nightmare.
> 
> You are right about this
> 
> I will close this issue as I am unable to re-reproduce this! thank you for your time

Randomly found this looking for a typescript solution

declaring the enum as an export did it for me.  Appreciate the tip 👍 
`export enum MyEnum { PROP1, PROP2 };`
