### ISSUE TITLE
Add support for TypeScript 4.6.x

### ISSUE THREAD

**Issue by willeastcott** [Swatinem/rollup-plugin-dts#200]
If I try to use `rollup-plugin-dts` in a `package.json` that has `typescript` 4.6.x as a peer dependency, I see:

![image](https://user-images.githubusercontent.com/697563/156143954-67b4af88-387f-402e-939c-46b3403d9e94.png)

It's because of this line:

https://github.com/Swatinem/rollup-plugin-dts/blob/master/package.json#L65

**Comment by igordanchenko** [comment]
@Swatinem, as I can see, the current peer dependency range was implemented in #176. However, the main ask in that ticket was to support TS 4.1, not necessarily prevent users from upgrading to a new TS version. And while I agree that "~" pinning is more semantically correct because TS doesn't strictly follow semver, it may be an overkill in this particular case, given that the plugin doesn't always break between minor TS releases. It would be great if you could give the peer dependency range pinning another thought.

**Comment by Swatinem** [comment]
I published a new version, and relaxed the `peerDependency` range.
