### ISSUE TITLE
[feat] esbuild plugin support

### ISSUE THREAD

**Issue by loynoir** [Swatinem/rollup-plugin-dts#260]
Would be nice to use this in `esbuild`.

**Comment by Swatinem** [comment]
Do you mean to use that as a plugin in esbuild?

I’m not sure how that would work. Also, the plugin expects a definition file as generated by typescript. Due to optional return type annotations, the real typescript compiler needs to typecheck and infer the return types for the declaration files. I don’t think esbulid does that (yet).
