### ISSUE TITLE
Support for "incremental" mode

### ISSUE THREAD

**Issue by aleclarson** [Swatinem/rollup-plugin-dts#28]
This plugin should respect `"incremental": true` in the local `tsconfig.json` module.

Also, `tsBuildInfoFile` should be supported. 👍

**Comment by Swatinem** [comment]
Since I’m experimenting with project references and `incremental` right now myself. I thought about:

just use `tsc` to compile `.ts` -> `.js` / `.d.ts`, and then use rollup to bundle up `.js` *without any transforms*, and `rollup-plugin-dts` to bundle up `.d.ts`.

Haven’t had too much time lately to work on it though.

**Comment by Swatinem** [comment]
This will not be implemented as per #29 
you can run tsc with `--incremental` and `declaration: true` / `emitDeclarationOnly: true` and then use the output files with this plugin
