### ISSUE TITLE
Support non-ambient ".ts" modules

### ISSUE THREAD

**Issue by aleclarson** [Swatinem/rollup-plugin-dts#31]
I'm curious why support for non-ambient (eg: `.ts` not `.d.ts`) definitions was removed.

I don't want this plugin to emit anything other than the `.d.ts` bundle, but it would be nice to avoid generating intermediate `.d.ts` modules. <s>Also, with `ts-loader` and `awesome-typescript-loader`, it's not possible to generate `.d.ts` modules if you want to use a forked process for type checking (eg: with [`fork-ts-checker-webpack-plugin`](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin)).</s>

To be clear, I don't want this plugin to perform type checking, either.

**Comment by aleclarson** [comment]
I just realized the dumbness of mentioning Webpack plugins in an issue about a Rollup plugin. 😂 I must've confused myself temporarily.

**Comment by Swatinem** [comment]
I gave my reasons in #29. In short, using the typescript compiler for anything else than just as a parser is really not-trivial.
And I don’t want to put in all the duplicated effort into supporting all the different ways how people want to build/manage their projects (like #28).
Easiest way is to delegate that task to other tools, such as the `tsc` cli itself.

For me personally the transition was really easy and smooth, see https://github.com/Swatinem/rollup-plugin-dts/commit/7ea4a025128216bc38e8bafcc6d5bc05fd04169d and https://github.com/eversport/intl-codegen/commit/412f1bf77fcc60179e888ca36ea118b99c0616cc

This also opens up the door to maybe kick out `ts-jest` as well at some point, since it starts to really annoy me recently. Also, as you see, I don’t need *any* plugin/loader anymore to bundle up my `.js` code anymore. Which is a win. So instead of N tools, each of which is different in some subtle ways, and supports a different set of features (like --incremental or project references), I try to rely on `tsc` only, without any other third party tools that could potentially break in surprising ways.

**Comment by aleclarson** [comment]
> In short, using the typescript compiler for anything else than just as a parser is really not-trivial.

It's not easy to generate ambient declarations from a set of `.ts` modules, and then feed those directly to `rollup-plugin-dts` to escape the need for intermediate files?

> And I don’t want to put in all the duplicated effort into supporting all the different ways how people want to build/manage their projects

Sure, but I don't see this as a slippery slope. All I want is to avoid intermediate files. :)

**Comment by Swatinem** [comment]
> All I want is to avoid intermediate files. :)

I thought the same some months ago, now I changed my mind about this :-)
