### ISSUE TITLE
Comments in d.ts dependencies are not included

### ISSUE THREAD

**Issue by rdmurphy** [Swatinem/rollup-plugin-dts#53]
Hello! 👋

Thank you for an excellent library — it's so cool how this takes advantage of how Rollup works to accomplish tree-shaking for `d.ts` files.

I noticed when I was experimenting with the plugin that comments that are present in files that are depended on are not included in the final output. I'm not sure if that's intentional, but IMO it may be nice to bring them over too if possible? I tend to use TypeScript primarily through VS Code, and it's really nice that the comments in `d.ts` are surfaced when you inspect a function.

I've prepared an example repo that shows this happening. If a function has a comment in the entrypoint, it'll be there. If something is commented in a dependency, the comment is dropped.

https://github.com/rdmurphy/rollup-plugin-dts-comments

Thank you!

**Comment by Swatinem** [comment]
Hi!

Thanks for the report. I have been looking into this but so far I wasn’t able to find out what exactly is going on. AFAICS, the plugin does everything correctly, but the comment is still removed…

**Comment by rdmurphy** [comment]
That's so weird! Thanks for looking into it. So is it like something Rollup is doing by default?

**Comment by rdmurphy** [comment]
Not 100% certain but [this issue may be related](https://github.com/rollup/rollup/issues/2943)? (And it mentions `rollup-plugin-dts` and suggests a fix, but doesn't appear to have made it over here. 🤔 )

**Comment by Swatinem** [comment]
Hm, I’m not sure. @aleclarson did some work on these tripple-slash references some time ago.

Just to ilustrate how `rollup-plugin-dts` works: The AST it hands of to rollup does not look *anything* like a real AST. For the file in question, it outputs a single function declaration that starts at offset `0` and includes the complete comment in its range. Rollup should just copy that range from the file without doing anything else… Which is why I have no idea why this happens…

**Comment by aleclarson** [comment]
@rdmurphy 	That issue is only about ["triple slash directives"](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html). I think your issue is to do with 
`export { square }`. If you use `export * from`, the comments are preserved, in my experience.

**Comment by Swatinem** [comment]
I was playing around with this a bit more because this is just such a weird case…
When you look at the code here: https://github.com/Swatinem/rollup-plugin-dts/commit/5f748781cd353b81f19a13c387c7db9d2b5465cb
The doc-comment of the first function that is exported is removed for whatever reason. When I reorder the `export from` statements in the main file, the functions are swapped and since now the function named `second` is the first one in the output file, and it is missing its doc-comment. Super weird.
I suspect that this is indeed a problem with upstream rollup, but I will need to somehow make reproduce this outside of the plugin…

**Comment by Swatinem** [comment]
@rdmurphy sorry for the very long delay. Can you try again with `1.1.10`? That should take care of this.

:man_facepalming: 

https://github.com/Swatinem/rollup-plugin-dts/commit/963809a3c1abca31e907bfc5cc7bba65b0652006#diff-7ecaa59e5bd947653babe0cb5f556221R85

Not the first time this misleading API has caused us problems. I will file a bug upstream in TS to hopefully get that fixed.

CC @aleclarson

**Comment by Swatinem** [comment]
https://github.com/microsoft/TypeScript/issues/33790 <- filed this upstream, because the API is super unintuitive and just causes problems IMO.

**Comment by rdmurphy** [comment]
@Swatinem No need to apologize! Thank you for figuring it out! I just updated my test repo and it appears to be working. 🙌

I'll give it a few more runs with a bigger project of mine and report back.
