### ISSUE TITLE
Importing from an `export = namespace` not supported

### ISSUE THREAD

**Issue by OmgImAlexis** [Swatinem/rollup-plugin-dts#93]
> Seems rollup-plugin-dts doesn't support import from namespace yet?:

Ref: https://github.com/egoist/tsup/issues/14#issuecomment-630220268

**Comment by Swatinem** [comment]
Copy-pasting from https://github.com/egoist/tsup/issues/14#issuecomment-630227883:

Sometimes the things from `@types` have really strange idioms in them, and its a nightmare to work with.

This example in particular. I *think*, this is whats going on:

* I treat TS `namespace` as an opaque "item". Due to declaration merging, you can have namespaces which have the same name as functions, which is basically the same as having an interface with members and a call signature.
* And in commonjs, you used to be able to `module.exports = fn_with_props`
* And then just `require` that, since the result is just any kind of value.
* But with ES modules, this is just not possible *cleanly*, unless you use some kind of "import default interop".
* And that is something that I don‘t know how to really translate to the `.d.ts` world. And TBH, I don‘t want to, since its something that is fundamentally different when using ES modules.

**Comment by trusktr** [comment]
I agree, let's support the ES Module future and not dwell on CommonJS pitfalls.

**Comment by IanVS** [comment]
Hi, is this still an issue?  I'm hitting problems when using tsup because of various sub-dependencies using `export =` in their .d.ts files, and I'm unsure what's needed to solve it.

**Comment by Swatinem** [comment]
This is still not supported, and I doubt I will add support for this myself. PRs welcome of course.

The question here would rather be: Why are you trying to bundle your sub-dependencies in the first place?

**Comment by IanVS** [comment]
I don't think I am.  But I'm not sure.  I'm trying to add a feature into Storybook, which has recently started using tsup.  Importing types from `fastify` is breaking the build, apparently because of this issue.  What configuration would I need to look for to see whether or not sub-dependencies are being bundled?  I've not worked with tsup before, and I don't have a great grasp of how it's all working right now.

**Comment by Swatinem** [comment]
> I've not worked with tsup before, and I don't have a great grasp of how it's all working

Neither have I 🤷🏻‍♂️ 

My plugin ignores external dependencies by default.

**Comment by Nick-Hopps** [comment]
Is it possible to make the output d.ts file using `export =` format to support both ESM and CJS?
