### ISSUE TITLE
Error: Note that you need plugins to import files that are not JavaScript

### ISSUE THREAD

**Issue by nonara** [Swatinem/rollup-plugin-dts#96]
This error happens whenever trying to use `dts()` in a project which has a `tsconfig.json` file with `"noEmit": true`, specified.

Possible related to https://github.com/rollup/plugins/issues/287

**Comment by Swatinem** [comment]
Hm, we possibly have to override that option here:

https://github.com/Swatinem/rollup-plugin-dts/blob/b92324da45eebe29ab852889798e954bb100f5e5/src/program.ts#L12-L27

Can you give a more detailed example? I suspect you are using the plugin with `.ts` files?

**Comment by nonara** [comment]
That did the trick. Thanks 😄

**Comment by castarco** [comment]
I don't think this is truly solved. Having the most simple configuration, just because I use import mapping... it crashes miserably, even though:
- I specified the paths in `package.json`'s `imports` field
- I also specified the paths in `tsconfig.json`'s `compilerOptions.paths` field.
- I passed these same paths to the plugin options.

I mean... `rollup-plugin-dts` is supposed to read TypeScript, and... it complains about it not being pure JavaScript...?
